{% set name = "clinfo" %}
{% set version = "3.0.25.02.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Oblomov/clinfo/archive/{{ version }}.tar.gz
  sha256: 48b77dc33315e6f760791a2984f98ea4bff28504ff37d460d8291585f49fcd3a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx or win]
  run:
    - {{ pin_compatible("ocl-icd") }}  # [linux]
    - {{ pin_compatible("khronos-opencl-icd-loader", max_pin=None) }}  # [osx or win]
test:
  requires:
    - pocl
  commands:
    - clinfo -l

about:
  home: https://github.com/Oblomov/clinfo
  license: CC0-1.0
  license_family: CC
  license_file: legalcode.txt
  summary: 'Print all known information about all available OpenCL platforms and devices in the system'

extra:
  recipe-maintainers:
    - isuruf
    - matthiasdiener
